version: '3'

services:
  nginx:
    restart: always
    build:
      context: ../../nginx
      dockerfile: Dockerfile
    container_name: nginx
    depends_on:
      - api
      - client
    ports:
      - "8080:80"

  api:
    build:
      context: ../../api
      dockerfile: Dockerfile
    container_name: api

  client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: ../../sys-stats
      dockerfile: Dockerfile
    container_name: client
    depends_on:
      - api
    volumes:
      - /home/observer/node_modules